Added Credential Provider for the access.logs.add event
imhotep/hass-unifi-access pull request #75
Opened 2024-09-10 20:26 UTC by jblattel

added ability to determine how the actor has initiated the access event - remotely (through access app or viewer) or at the reader itself with a phone or nfc card.

2024-09-11 18:36 UTC, imhotep commented
@jblattel this LGTM but I would like to test it before merging. I will see if I can do that in the next few days. Were you able to verify all the different authentication methods?

2024-09-13 16:10 UTC, jblattel commented
> @jblattel this LGTM but I would like to test it before merging. I will see if I can do that in the next few days. Were you able to verify all the different authentication methods?

@imhotep - well to the extent that I know of (NFC card, pin code, through the phone app, and Mobile phone NFC tap) - I did not test any 3rd party NFC devices - but presume they will come through as "NFC"

2024-09-23 15:59 UTC, imhotep requested changes

2024-09-23 15:59 UTC, imhotep commented on custom_components/unifi_access/hub.py
>                                  )
```suggestion
                                _LOGGER.info(
                                    "Door name %s with id %s accessed by %s. authentication %s, access type: %s",
                                    existing_door.name,
                                    door_id,
                                    actor,
                                    authentication,
                                    access_type,
                                )
```

Also can you update the README.md to add this new information?

2024-10-02 15:10 UTC, merged